# En ruff.toml
line-length = 120
indent-width = 4

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint]
select = ["E", "F", "I"]
ignore = []

[lint.isort]
combine-as-imports = true
force-sort-within-sections = true
