#!/usr/bin/env bash
#  █▀ █▀▀ █▄░█ ▀█▀ █░█  ┎┤ Data Engineering ├┒
#  ▄█ ██▄ █░▀█ ░█░ █▄█  ┖┤    INSTALADOR    ├┚
#              .studio
#  script instalador
#   Author: @elepistemedev
#   url: https://github.com/elepistemedev

CRE=$(tput setaf 1)
CYE=$(tput setaf 3)
CGR=$(tput setaf 2)
CBL=$(tput setaf 4)
BLD=$(tput bold)
CNC=$(tput sgr0)

backup_folder=~/.SENTUBackup
date=$(date +%Y%m%d-%H%M%S)

# Función para ejecutar un bloque de script y mostrar un mensaje de error si falla
function ejecutar_bloque() {
  local script="$1"
  local mensaje="$2"

  sh ~/.dotfiles/scripts/login.sh
  echo "$mensaje"
  if sh "$script"; then
    echo "Ejecución exitosa"
  else
    echo "**ERROR:** Falló la ejecución de '$script'"
    exit 1
  fi
}

logo () {

    local text="${1:?}"
    echo -en "
  █▀ █▀▀ █▄░█ ▀█▀ █░█  ┎┤ Data Engineering ├┒
  ▄█ ██▄ █░▀█ ░█░ █▄█  ┖┤    INSTALADOR    ├┚
              .studio
    Dotfiles\n\n"
    printf ' %s [%s%s %s%s %s]%s\n\n' "${CRE}" "${CNC}" "${CYE}" "${text}" "${CNC}" "${CRE}" "${CNC}"
}

########## ---------- You must not run this as root ---------- ##########

if [ "$(id -u)" = 0 ]; then
    echo "Este script NO DEBE ser ejecutado como un usuario root."
    exit 1
fi

home_dir=$HOME
current_dir=$(pwd)

if [ "$current_dir" != "$home_dir" ]; then
    printf "%s%sEl script debe ser ejecutado desde el directorio HOME.%s\n" "${BLD}" "${CYE}" "${CNC}"
    exit 1
fi

########## ---------- Bienvenido ---------- ##########

logo "Bienvenido!"
printf '%s%sEste script comprobará si tiene las dependencias necesarias y, en caso contrario, las instalará. Luego, clonará mi repositorio en su directorio HOME.\nDespués de eso, creará una copia de seguridad de sus archivos y luego copiará los nuevos archivos a su computadora.\n\nMis archivos dot NO modifican ninguna de las configuraciones de su sistema.\ nSe le solicitará su contraseña de root para instalar las dependencias que faltan y/o cambiar a zsh shell si no es la predeterminada.\n\nEste script no tiene el poder potencial de dañar su sistema, solo copia archivos de mi repositorio a su Directorio HOME.%s\n\n' "${BLD}" "${CRE}" "${CNC}"

while true; do
    read -rp " Deseas continuar? [y/N]: " yn
    case $yn in
        [Yy]* ) break ;;
        [Nn]* ) exit ;;
        * ) printf " Error: solo escribe 'y' o 'n'\n\n" ;;
    esac
done
clear

########## ---------- Install packages ---------- ##########

logo "Instalando paquetes necesarios.."

dependencias=(alacritty base-devel brightnessctl bspwm dunst feh firefox geany git kitty imagemagick jq \
                docker jdk-openjdk\
                jgmenu libwebp lsd maim mpc mpd neovim ncmpcpp pamixer pacman-contrib \
                papirus-icon-theme physlock picom playerctl polybar polkit-gnome python-gobject ranger \
                redshift rofi ruby rustup sxhkd tmux ttf-inconsolata ttf-jetbrains-mono ttf-jetbrains-mono-nerd \
                ttf-joypixels ttf-terminus-nerd ueberzug webp-pixbuf-loader xclip xdg-user-dirs \
                xdo xdotool xorg-xdpyinfo xorg-xkill xorg-xprop xorg-xrandr xorg-xsetroot \
                xorg-xwininfo zsh zsh-autosuggestions zsh-history-substring-search zsh-syntax-highlighting)

is_installed() {
    pacman -Q "$1" &> /dev/null
}

printf "%s%sChecking for required packages...%s\n" "${BLD}" "${CBL}" "${CNC}"
for paquete in "${dependencias[@]}"; do
    if ! is_installed "$paquete"; then
        if sudo pacman -S "$paquete" --noconfirm >/dev/null 2>> SENTUError.log; then
            printf "%s%s%s %sse ha instalado correctamente.%s\n" "${BLD}" "${CYE}" "$paquete" "${CBL}" "${CNC}"
            sleep 1
        else
            printf "%s%s%s %sno se ha instalado correctamente. Ver %sSENTUError.log %spara más detalles.%s\n" "${BLD}" "${CYE}" "$paquete" "${CRE}" "${CBL}" "${CRE}" "${CNC}"
            sleep 1
        fi
    else
        printf '%s%s%s %s¡Ya está instalado en su sistema!%s\n' "${BLD}" "${CYE}" "$paquete" "${CGR}" "${CNC}"
        sleep 1
    fi
done
sleep 5
clear

########## ---------- Preparing Folders ---------- ##########

# Verifies if the archive user-dirs.dirs doesn't exist in ~/.config
if [ ! -e "$HOME/.config/user-dirs.dirs" ]; then
    xdg-user-dirs-update
fi

########## ---------- Cloning the SENTU! ---------- ##########

logo "Downloading dotfiles"

repo_url="https://github.com/elepistemedev/dotfiles"
repo_dir="$HOME/dotfiles"
branch_name="archlinux"

# Verifies if the folder of the repository exists, and if it does, deletes it
if [ -d "$repo_dir" ]; then
    printf "Eliminando el repositorio de dotfiles existente\n"
    rm -rf "$repo_dir"
fi

# Clone the repository
printf "Clonando dotfiles desde %s\n" "$repo_url"
git clone --branch "$branch_name" --depth=1 "$repo_url" "$repo_dir"
sleep 2
clear

########## ---------- Respaldando Archivos ---------- ##########

logo "Respaldando Archivos"

printf "Si ya tienes una configuración NEOVIM potente y súper Pro, escribe 'n' en la siguiente pregunta. Si responde 'y', su configuración de neovim se moverá al directorio de respaldo.\n\n"

while true; do
    read -rp "¿Quieres probar mi configuración de nvim? (t/n): " try_nvim
    if [[ "$try_nvim" == "y" || "$try_nvim" == "n" ]]; then
        break
    else
        echo "Entrada inválida. Por favor ingrese 'y' o 'n'."
    fi
done

printf "\nLos archivos de copia de seguridad se almacenarán en %s%s%s/.SENTUBackup%s \n\n" "${BLD}" "${CRE}" "$HOME" "${CNC}"
sleep 10

[ ! -d "$backup_folder" ] && mkdir -p "$backup_folder"

for folder in bspwm alacritty picom rofi eww sxhkd dunst kitty polybar ncmpcpp ranger tmux zsh mpd paru; do
    if [ -d "$HOME/.config/$folder" ]; then
        if mv "$HOME/.config/$folder" "$backup_folder/${folder}_$date" 2>> SENTUError.log; then
            printf "%s%s%s carpeta respaldada exitosamente en %s%s/%s_%s%s\n" "${BLD}" "${CGR}" "$folder" "${CBL}" "$backup_folder" "$folder" "$date" "${CNC}"
            sleep 1
        else
            printf "%s%s No se pudo realizar la copia de seguridad de la carpeta %s. Ver %sSENTUError.log%s\n" "${BLD}" "${CRE}" "$folder" "${CBL}" "${CNC}"
            sleep 1
        fi
    else
        printf "%s%s%s La carpeta no existe, %sno se necesita copia de seguridad.%s\n" "${BLD}" "${CGR}" "$folder" "${CYE}" "${CNC}"
        sleep 1
    fi
done

if [[ $try_nvim == "y" ]]; then
        # Backup nvim
    if [ -d "$HOME/.config/nvim" ]; then
        if mv "$HOME/.config/nvim" "$backup_folder/nvim_$date" 2>> SENTUError.log; then
                printf "%s%sCarpeta nvim respaldada exitosamente en %s%s/nvim_%s%s\n" "${BLD}" "${CGR}" "${CBL}" "$backup_folder" "$date" "${CNC}"
                sleep 1
            else
                printf "%s%sNo se pudo realizar la copia de seguridad de la carpeta nvim. Ver %sSENTUError.log%s\n" "${BLD}" "${CRE}" "${CBL}" "${CNC}"
                sleep 1
        fi
        else
            printf "%s%sLa carpeta nvim no existe, %sno se necesita copia de seguridad%s\n" "${BLD}" "${CGR}" "${CYE}" "${CNC}"
            sleep 1
    fi
fi

for folder in "$HOME"/.mozilla/firefox/*.default-release/chrome; do
    if [ -d "$folder" ]; then
        if mv "$folder" "$backup_folder"/chrome_"$date" 2>> SENTUError.log; then
            printf "%s%sCarpeta de Chrome respaldada exitosamente en %s%s/chrome_%s%s\n" "${BLD}" "${CGR}" "${CBL}" "$backup_folder" "${date}" "${CNC}"
        else
            printf "%s%sNo se pudo realizar la copia de seguridad de la carpeta Chrome. Ver %sSENTUError.log%s\n" "${BLD}" "${CRE}" "${CBL}" "${CNC}"
        fi
    else
        printf "%s%sLa carpeta Chrome no existe, %sno se necesita copia de seguridad%s\n" "${BLD}" "${CGR}" "${CYE}" "${CNC}"
    fi
done

for file in "$HOME"/.mozilla/firefox/*.default-release/user.js; do
    if [ -f "$file" ]; then
        if mv "$file" "$backup_folder"/user.js_"$date" 2>> SENTUError.log; then
            printf "%s%sSe realizó una copia de seguridad exitosa del archivo user.js en %s%s/user.js_%s%s\n" "${BLD}" "${CGR}" "${CBL}" "$backup_folder" "${date}" "${CNC}"
        else
            printf "%s%sNo se pudo realizar la copia de seguridad del archivo user.js. Ver %sSENTUError.log%s\n" "${BLD}" "${CRE}" "${CBL}" "${CNC}"
        fi
    else
        printf "%s%sEl archivo user.js no existe, %sno se necesita copia de seguridad%s\n" "${BLD}" "${CGR}" "${CYE}" "${CNC}"
    fi
done

if [ -f ~/.zshrc ]; then
    if mv ~/.zshrc "$backup_folder"/.zshrc_"$date" 2>> SENTUError.log; then
        printf "%s%sSe realizó una copia de seguridad exitosa del archivo .zshrc en %s%s/.zshrc_%s%s\n" "${BLD}" "${CGR}" "${CBL}" "$backup_folder" "${date}" "${CNC}"
    else
        printf "%s%sNo se pudo realizar la copia de seguridad del archivo .zshrc. Ver %sSENTUError.log%s\n" "${BLD}" "${CRE}" "${CBL}" "${CNC}"
    fi
else
    printf "%s%sEl archivo .zshrc no existe, %sno se necesita copia de seguridad%s\n" "${BLD}" "${CGR}" "${CYE}" "${CNC}"
fi

printf "%s%sCompletado!!%s\n\n" "${BLD}" "${CGR}" "${CNC}"
sleep 5

########## ---------- Copy the SENTU! ---------- ##########

logo "Instalando dotfiles.."
printf "Copiar archivos a los directorios respectivos..\n"

[ ! -d ~/.config ] && mkdir -p ~/.config
[ ! -d ~/.local/bin ] && mkdir -p ~/.local/bin
[ ! -d ~/.local/share ] && mkdir -p ~/.local/share

for dirs in ~/dotfiles/config/*; do
    dir_name=$(basename "$dirs")
# If the directory is nvim and the user doesn't want to try it, skip this loop
    if [[ $dir_name == "nvim" && $try_nvim != "y" ]]; then
        continue
    fi
    if cp -R "${dirs}" ~/.config/ 2>> SENTUError.log; then
        printf "%s%s%s %sconfiguración instalada exitosamente%s\n" "${BLD}" "${CYE}" "${dir_name}" "${CGR}" "${CNC}"
        sleep 1
    else
        printf "%s%s%s %sNo se pudo instalar la configuración; consulte %sSENTUError.log %spara obtener más detalles.%s\n" "${BLD}" "${CYE}" "${dir_name}" "${CRE}" "${CBL}" "${CRE}" "${CNC}"
        sleep 1
    fi
done

for folder in applications asciiart fonts startup-page; do
    if cp -R ~/dotfiles/misc/$folder ~/.local/share/ 2>> SENTUError.log; then
        printf "%s%s%s %scarpeta copiada exitosamente!%s\n" "${BLD}" "${CYE}" "$folder" "${CGR}" "${CNC}"
        sleep 1
    else
        printf "%s%s%s %sLa carpeta no se pudo copiar, consulte %sSENTUError.log %s para obtener más detalles..%s\n" "${BLD}" "${CYE}" "$folder" "${CRE}" "${CBL}" "${CRE}" "${CNC}"
        sleep 1
    fi
done

if cp -R ~/dotfiles/misc/bin ~/.local/ 2>> SENTUError.log; then
    printf "%s%sCarpeta bin%s copiada con éxito!%s\n" "${BLD}" "${CYE}" "${CGR}" "${CNC}"
    sleep 1
else
    printf "%s%sNo se pudo copiar la carpeta bin %s; consulte %sSENTUError.log %s para obtener más detalles.%s\n" "${BLD}" "${CYE}" "${CRE}" "${CBL}" "${CRE}" "${CNC}"
    sleep 1
fi

if cp -R ~/dotfiles/misc/firefox/* ~/.mozilla/firefox/*.default-release/ 2>> SENTUError.log; then
    printf "%s%s¡El tema de Firefox %s se copió con éxito!%s\n" "${BLD}" "${CYE}" "${CGR}" "${CNC}"
    sleep 1
else
    printf "%s%sEl tema de Firefox %sno se pudo copiar; consulte %sSENTUError.log %spara obtener más detalles.%s\n" "${BLD}" "${CYE}" "${CRE}" "${CBL}" "${CRE}" "${CNC}"
    sleep 1
fi

sed -i "s/user_pref(\"browser.startup.homepage\", \"file:\/\/\/home\/z0mbi3\/.local\/share\/startup-page\/index.html\")/user_pref(\"browser.startup.homepage\", \"file:\/\/\/home\/$USER\/.local\/share\/startup-page\/index.html\")/" "$HOME"/.mozilla/firefox/*.default-release/user.js
sed -i "s/name: 'gh0stzk'/name: '$USER'/" "$HOME"/.local/share/startup-page/config.js
cp -f "$HOME"/dotfiles/home/.zshrc "$HOME"
fc-cache -rv >/dev/null 2>&1

printf "\n\n%s%sArchivos copiados Satisfactoriamente!!%s\n" "${BLD}" "${CGR}" "${CNC}"
sleep 5

########## ---------- Instalando Paru & others ---------- ##########

logo "instalando Paru, Eww, tdrop & xqp"

# Instalando Paru
if command -v paru >/dev/null 2>&1; then
    printf "%s%sParu ya se encuentra instalado%s\n" "${BLD}" "${CGR}" "${CNC}"
else
    printf "%s%sInstalando paru%s\n" "${BLD}" "${CBL}" "${CNC}"
    {
        cd "$HOME" || exit
        git clone https://aur.archlinux.org/paru-bin.git
        cd paru-bin || exit
        makepkg -si --noconfirm
        } || {
        printf "\n%s%sNo se pudo instalar Paru. Es posible que tengas que instalarlo manualmente.%s\n" "${BLD}" "${CRE}" "${CNC}"
    }
fi

# Instalando tdrop for scratchpads
if command -v tdrop >/dev/null 2>&1; then
    printf "\n%s%sTdrop ya está instalado%s\n" "${BLD}" "${CGR}" "${CNC}"
else
    printf "\n%s%sInstalando tdrop, esto podría ser rápido!%s\n" "${BLD}" "${CBL}" "${CNC}"
    paru -S tdrop-git --skipreview --noconfirm
fi

# Instalando xqp
if command -v xqp >/dev/null 2>&1; then
    printf "\n%s%sxqp ya se encuentra instalado%s\n" "${BLD}" "${CGR}" "${CNC}"
else
    printf "\n%s%sInstalando xqp, esto podría ser rápido!%s\n" "${BLD}" "${CBL}" "${CNC}"
    paru -S xqp --skipreview --noconfirm
fi

# Instalando Eww
if command -v eww >/dev/null 2>&1; then
    printf "\n%s%sEww ya se encuentra instalado%s\n" "${BLD}" "${CGR}" "${CNC}"
else
    printf "\n%s%sInstalando Eww, esto podría tomar 10 mins o más.%s\n" "${BLD}" "${CBL}" "${CNC}"
    {
        sudo pacman -S rustup --noconfirm
        cd "$HOME" || exit
        git clone https://github.com/elkowar/eww
        cd eww || exit
        cargo build --release --no-default-features --features x11
        sudo install -m 755 "$HOME/eww/target/release/eww" -t /usr/bin/
        cd "$HOME" || exit
        rm -rf {paru-bin,.cargo,.rustup,eww}
        } || {
        printf "\n%s%sFallo al instalar Eww. Puedes instalarlo manualmente%s\n" "${BLD}" "${CRE}" "${CNC}"
    }
fi

########## ---------- Enabling MPD service ---------- ##########

logo "Habilitando el servicio mpd"

# Verifica si el servicio mpd está habilitado a nivel global (sistema)
if systemctl is-enabled --quiet mpd.service; then
    printf "\n%s%sDeshabilitar y detener el servicio mpd global%s\n" "${BLD}" "${CBL}" "${CNC}"
    sudo systemctl stop mpd.service
    sudo systemctl disable mpd.service
fi

printf "\n%s%sHabilitar e iniciar el servicio mpd a nivel de usuario%s\n" "${BLD}" "${CYE}" "${CNC}"
systemctl --user enable --now mpd.service

printf "%s%sDone!!%s\n\n" "${BLD}" "${CGR}" "${CNC}"
sleep 2

########## --------- Instalar Script ---------- ##########
# Cargo
ejecutar_bloque ~/dotfiles/scripts/install-cargo-app.sh "Ejecutando instalación de dependencias con cargo"

# Tmux y complementos
ejecutar_bloque ~/dotfiles/scripts/install-tmux.sh "Ejecutando instalación de Tmux y complementos para Tmux"

# Fonts
ejecutar_bloque ~/dotfiles/scripts/install-fonts.sh "Ejecutando instalación de las fuentes de letras necesarias"



########## --------- Docker setup ---------- ##########


sudo groupadd docker
sudo usermod -aG docker $USER

sudo systemctl start docker.service
sudo systemctl enable docker.service
sudo systemctl start docker

DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
mkdir -p $DOCKER_CONFIG/cli-plugins
curl -SL https://github.com/docker/compose/releases/download/v2.27.2/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose

chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

########## --------- Changing shell to zsh ---------- ##########

logo "Cambiando shell to zsh"

if [[ $SHELL != "/usr/bin/zsh" ]]; then
    printf "\n%s%sCambiando tu shell a zsh. Se necesita su contraseña de root.%s\n\n" "${BLD}" "${CYE}" "${CNC}"
    # Cambia la shell a zsh
    chsh -s /usr/bin/zsh
    printf "%s%sShell cambió a zsh. Por favor reinicie.%s\n\n" "${BLD}" "${CGR}" "${CNC}"
else
    printf "%s%sTu shell ya es zsh\n¡Adiós! instalación finalizada, ahora reinicie%s\n" "${BLD}" "${CGR}" "${CNC}"
fi
zsh
