# /home/el/.config/tmuxinator/sentu.yml

name: sentu
root: ~/sentu/

# on_project_start:
on_project_exit: clear
windows:
  - server:
      layout: main-horizontal #even-vertical
      panes:
        - frontend:
          - clear
        - backend:
          - clear
  - music: cmus
  - logs:
  - vim: clear
  - db:
  - shell: sleep 5; cmus-remote -p && clear
