manager: dnf
update_command: 
  - sudo
  - dnf
  - update
  - -y
install_command:
  - sudo
  - dnf
  - install
  - -y
  - --allowerasing
repositories:
  rpmfusion-nonfree:
    - sudo
    - dnf
    - install
    - -y
    - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{version}.noarch.rpm"
  rpmfusion-free:
    - sudo
    - dnf
    - install
    - -y
    - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{version}.noarch.rpm"
  docker:
    - sudo
    - dnf
    - config-manager
    - addrepo
    - --from-repofile=https://download.docker.com/linux/fedora/docker-ce.repo
dependencies:
  core:
    - git
    - curl
    - wget
    - gcc
    - make
    - unzip
    - zsh
    - golang
    - cargo
    - g++
    - python3
    - ruby
    - unrar
    - p7zip
    - p7zip-plugins
    - xdg-user-dirs
    - lsd
    - java
    - dnf-utils
    - flatpak
    - kernel-devel
    - automake
    - perl
    - elfutils-libelf-devel
  extended:
    - lazygit
    - ripgrep
    - fd-find
    - neovim
    - fastfetch
    - util-linux-user
    - anacron
    - python3-neovim
    - kitty
    - lua-devel
    - luarocks
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
    - bat
    - fzf
    - httpie
    - tmux
    - htop
    - proselint
    - lm_sensors
    - discord
    - alacritty
    - kde-connect
    - kdenlive
    - openshot
    - vlc
    - mpv
    - gnome-mpv
    - soundconverter
    - audacity
    - muse
    - lmms
    - amarok
    - flowblade
    - dnf-plugins-core
    - xine-lib
    - xine-lib-extras
    - xine-lib-extras-freeworld
    - libdvdread
    - libdvdnav
    - lsdvd
    - libdvbpsi
    - ffmpeg
    - libmatroska
    - xvidcore
    - gimp
    - inkscape
    - libreoffice-writer
    - libreoffice-calc
    - libreoffice-impress
    - libreoffice-draw
    - libreoffice-langpack-es
    - gstreamer1-devel
    - gstreamer1-plugins-base-tools
    - gstreamer1-doc
    - gstreamer1-plugins-base-devel
    - gstreamer1-plugins-good
    - gstreamer1-plugins-good-extras
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-bad-free-devel
